# == INSTRUCTIONS FOR SETTING UP TRAVIS (and GitHub Pages) ==
#
# 1. Find this repository in your Travis-CI dashboard.
#    open settings and add an environment variable called
#    GITHUB_ACCESS_TOKEN and set it to your personal access token.addons:
#    See: https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line
#
#    **DO NOT TURN ON 'Display value in build log'!!!!**
#
# 2. Push the code to the repository.
# 3. Set the GitHub Pages source in the GitHub repository settings to the
#    gh-pages branch.

language: node_js
node_js:
 - "12"

addons:
 apt:
  packages:
   - libgconf-2-4 # cypress binary dependency

env:
 - DEPLOY_ENV=POSTWOMAN_IO

cache:
 npm: true
 directories:
  - "node_modules"
  - ~/.cache

branches:
 only:
  - "master"

install:
 - "npm install firebase-tools"
 - "npm install"

before_script:
 - "npm run test"

script:
 - "cd functions"
 - "npm install"
 - "cd .."
 - "npm run generate"

notifications:
  webhooks: https://www.travisbuddy.com

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
