# == INSTRUCTIONS FOR SETTING UP TRAVIS (and GitHub Pages) ==
#
# 1. Find this repository in your Travis-CI dashboard.
#    open settings and add an environment variable called
#    GITHUB_ACCESS_TOKEN and set it to your personal access token.addons:
#    See: https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line
#
#    **DO NOT TURN ON 'Display value in build log'!!!!**
#
# 2. Push the code to the repository.
# 3. Set the GitHub Pages source in the GitHub repository settings to the
#    gh-pages branch.

language: node_js
node_js:
 - "12"

env:
 - DEPLOY_ENV=POSTWOMAN_IO

addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4

cache:
  npm: true
  directories:
  - ~/.cache

branches:
 only:
  - "master"

install:
  - npm ci
  - "npm run generate"

notifications:
  webhooks: https://www.travisbuddy.com

deploy:
 provider: pages
 skip-cleanup: true
 # Refer to: https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
 github-token: $GITHUB_ACCESS_TOKEN
 target-branch: gh-pages
 local-dir: dist
 on:
  branch: master

before_install:
 - chmod +x prdeploy.sh

after_success:
 - ./prdeploy.sh